<a href="https://colab.research.google.com/github/mq6778duk-coder/Mylecture/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B3%BC%EC%A0%9C2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv(
    "/content/BindingDB_BindingDB_Articles.tsv",
    sep="\t",
    engine="python",
    on_bad_lines="skip")
df.head()

,BindingDB Reactant_set_id,Ligand SMILES,Ligand InChI,Ligand InChI Key,BindingDB MonomerID,BindingDB Ligand Name,Target Name,Target Source Organism According to Curator or DataSource,Ki (nM),IC50 (nM),...,UniProt (SwissProt) Recommended Name of Target Chain 50,UniProt (SwissProt) Entry Name of Target Chain 50,UniProt (SwissProt) Primary ID of Target Chain 50,UniProt (SwissProt) Secondary ID(s) of Target Chain 50,UniProt (SwissProt) Alternative ID(s) of Target Chain 50,UniProt (TrEMBL) Submitted Name of Target Chain 50,UniProt (TrEMBL) Entry Name of Target Chain 50,UniProt (TrEMBL) Primary ID of Target Chain 50,UniProt (TrEMBL) Secondary ID(s) of Target Chain 50,UniProt (TrEMBL) Alternative ID(s) of Target Chain 50
0,9825,COc1cc2c(Nc3ccc(Cl)cc3Cl)c(cnc2cc1OCCCN1CCN(C)...,InChI=1S/C25H27Cl2N5O2/c1-31-7-9-32(10-8-31)6-...,MVQUQGLRQPMJPU-UHFFFAOYSA-N,4521,"4-[(2,4-dichlorophenyl)amino]-6-methoxy-7-[3-(...",Proto-oncogene tyrosine-protein kinase Src,Homo sapiens,NaN,8.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9826,COc1cc2c(Nc3cc(OC)c(OC)c(OC)c3)c(cnc2cc1OCCCN1...,InChI=1S/C28H35N5O5/c1-32-8-10-33(11-9-32)7-6-...,VOUVVBUKNLBXGS-UHFFFAOYSA-N,6121,6-methoxy-7-[3-(4-methylpiperazin-1-yl)propoxy...,Proto-oncogene tyrosine-protein kinase Src,Homo sapiens,NaN,5.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9827,COCCOc1cc2ncc(C#N)c(Nc3cc(OC)c(Cl)cc3Cl)c2cc1O...,InChI=1S/C23H23Cl2N3O5/c1-29-4-6-32-21-8-15-18...,VXEOIAFZWQMOEP-UHFFFAOYSA-N,6122,"4-[(2,4-dichloro-5-methoxyphenyl)amino]-6,7-bi...",Proto-oncogene tyrosine-protein kinase Src,Homo sapiens,NaN,2.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9828,COCCOc1cc2ncc(C#N)c(Nc3ccc(Cl)cc3Cl)c2cc1OCCOC,InChI=1S/C22H21Cl2N3O4/c1-28-5-7-30-20-10-16-1...,DTLASHUZTAPRBX-UHFFFAOYSA-N,6123,"4-[(2,4-dichlorophenyl)amino]-6,7-bis(2-methox...",Proto-oncogene tyrosine-protein kinase Src,Homo sapiens,NaN,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9829,COCCOc1cc2ncc(C#N)c(Nc3cc(OC)c(OC)c(OC)c3)c2cc...,InChI=1S/C25H29N3O7/c1-29-6-8-34-20-12-18-19(1...,BTBPPLGKNLXRGR-UHFFFAOYSA-N,6124,"6,7-bis(2-methoxyethoxy)-4-[(3,4,5-trimethoxyp...",Proto-oncogene tyrosine-protein kinase Src,Homo sapiens,NaN,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:

df = df[["BindingDB MonomerID", "IC50 (nM)"]]
df["IC50 (nM)"] = pd.to_numeric(df["IC50 (nM)"], errors="coerce")
df = df.dropna(subset=["IC50 (nM)"])

result = df.groupby("BindingDB MonomerID")["IC50 (nM)"].agg(
    Mean="mean",
    Median="median",
    Max="max",
    Min="min"
)

result.head(10).style.format("{:.2f}")

In [9]:
display(result)

                             Mean    Median       Max      Min
BindingDB MonomerID
1                    21000.000000   21000.0   21000.0  21000.0
2                    66833.333333  100000.0  100000.0    500.0
19                      18.000000      18.0      18.0     18.0
21                     977.000000     300.0    3600.0     22.0
150                     15.000000      15.0      15.0     15.0
...                           ...       ...       ...      ...
50534770               350.000000     350.0     350.0    350.0
50540495              1871.000000    1871.0    1871.0   1871.0
50581215              2710.000000    2710.0    2710.0   2710.0
50584383              2170.000000    2170.0    2170.0   2170.0
50593239              1650.000000    1650.0    1650.0   1650.0

[33305 rows x 4 columns]